#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

isDebianPackageInstalled() {
  dpkg-query -W -f='${Status}' $1 2>/dev/null | grep -q 'ok installed'
}

installDebianPackage() {
  if ! isDebianPackageInstalled $1
  then
    sudo apt -y install $1
  fi
}

installNpmPackage() {
  if ! which $1 > /dev/null
  then
    npm -g install $1
  fi
}

# YouCompleteMe
installDebianPackage libclang-dev
installDebianPackage build-essential
installDebianPackage cmake
installDebianPackage python3-dev
cd ~/.vim/bundle/YouCompleteMe
python3 install.py --go-completer --ts-completer --java-completer --clang-completer

# Command-T
installDebianPackage ruby-dev
sudo snap install --classic go
cd ~/.vim/bundle/Command-T/ruby/command-t/ext/command-t/
ruby extconf.rb
make

# Syntastic: json
installNpmPackage jsonlint

# Syntastic: javascript
installNpmPackage jshint

# Syntastic: shell
installDebianPackage shellcheck

# The Silver Searcher
installDebianPackage silversearcher-ag

# Airline (needs special fonts)
if ! [[ -r ~/.fonts/PowerlineSymbols.otf ]]
then
  mkdir -p ~/.fonts
  cd ~/.fonts
  wget https://github.com/Lokaltog/powerline/raw/develop/font/PowerlineSymbols.otf
  fc-cache -vf ~/.fonts/
  mkdir -p ~/.config/fontconfig/conf.d
  cd ~/.config/fontconfig/conf.d
  wget https://github.com/Lokaltog/powerline/raw/develop/font/10-powerline-symbols.conf
fi

# Tern - http://ternjs.net
cd ~/.vim/bundle/tern_for_vim
npm install

# Tern Meteor config
curl --silent https://raw.githubusercontent.com/Slava/tern-meteor/master/meteor.js > ~/.vim/bundle/tern_for_vim/node_modules/tern/plugin/meteor.js
